USE [master]
GO
/****** Object:  Database [Nbp]    Script Date: 18.02.2022 12:28:34 ******/
CREATE DATABASE [Nbp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Nbp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Nbp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Nbp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Nbp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Nbp] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Nbp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Nbp] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Nbp] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Nbp] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Nbp] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Nbp] SET ARITHABORT OFF 
GO
ALTER DATABASE [Nbp] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Nbp] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Nbp] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Nbp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Nbp] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Nbp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Nbp] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Nbp] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Nbp] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Nbp] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Nbp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Nbp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Nbp] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Nbp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Nbp] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Nbp] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Nbp] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Nbp] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Nbp] SET  MULTI_USER 
GO
ALTER DATABASE [Nbp] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Nbp] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Nbp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Nbp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Nbp] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Nbp] SET QUERY_STORE = OFF
GO
USE [Nbp]
GO
/****** Object:  Table [dbo].[Currencies]    Script Date: 18.02.2022 12:28:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Currencies](
	[Currency] [nvarchar](50) NOT NULL,
	[Code] [nvarchar](3) NOT NULL,
	[Value] [float] NOT NULL,
	[LastUpdate] [datetime] NOT NULL,
 CONSTRAINT [PK_Currencies] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Nbp] SET  READ_WRITE 
GO
